"""Gold zone: business-ready aggregates + report generation.

Gold tables answer questions people actually ask:
- monthly spend trend
- top merchants / categories
- per-account summary
- refund & failure rates
Gold is small — these are the tables you'd paste into Sheets, feed a BI tool,
or hand to a stakeholder.
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

from .lake import read_partitioned, write_table

DATASET = "transactions"


def monthly_summary(df: pd.DataFrame) -> pd.DataFrame:
    completed = df[df["status"] == "completed"]
    g = (completed.groupby(["year", "month"], as_index=False)
         .agg(total_spend=("amount_abs", "sum"),
              txn_count=("transaction_id", "count"),
              avg_txn=("amount_abs", "mean"),
              active_accounts=("account_id", "nunique")))
    g["total_spend"] = g["total_spend"].round(2)
    g["avg_txn"] = g["avg_txn"].round(2)
    return g.sort_values(["year", "month"])


def top_merchants(df: pd.DataFrame, n: int = 10) -> pd.DataFrame:
    completed = df[df["status"] == "completed"]
    g = (completed.groupby("merchant", as_index=False)
         .agg(total_spend=("amount_abs", "sum"),
              txn_count=("transaction_id", "count")))
    g["total_spend"] = g["total_spend"].round(2)
    return g.sort_values("total_spend", ascending=False).head(n)


def category_breakdown(df: pd.DataFrame) -> pd.DataFrame:
    completed = df[df["status"] == "completed"]
    g = (completed.groupby("category", as_index=False)
         .agg(total_spend=("amount_abs", "sum"),
              txn_count=("transaction_id", "count"),
              avg_txn=("amount_abs", "mean")))
    total = g["total_spend"].sum()
    g["pct_of_spend"] = (100 * g["total_spend"] / total).round(1)
    g["total_spend"] = g["total_spend"].round(2)
    g["avg_txn"] = g["avg_txn"].round(2)
    return g.sort_values("total_spend", ascending=False)


def account_summary(df: pd.DataFrame) -> pd.DataFrame:
    g = (df.groupby("account_id", as_index=False)
         .agg(total_spend=("amount_abs", "sum"),
              txn_count=("transaction_id", "count"),
              refund_count=("is_refund", "sum"),
              first_txn=("timestamp", "min"),
              last_txn=("timestamp", "max")))
    g["total_spend"] = g["total_spend"].round(2)
    return g.sort_values("total_spend", ascending=False)


def health_metrics(df: pd.DataFrame) -> pd.DataFrame:
    return pd.DataFrame([{
        "total_transactions": len(df),
        "refund_rate_pct": round(100 * df["is_refund"].mean(), 2),
        "failure_rate_pct": round(100 * (df["status"] == "failed").mean(), 2),
        "weekend_share_pct": round(100 * df["is_weekend"].mean(), 2),
    }])


def run(cfg: dict) -> dict[str, pd.DataFrame]:
    silver_df = read_partitioned(cfg, "silver", DATASET)

    tables = {
        "monthly_summary": monthly_summary(silver_df),
        "top_merchants": top_merchants(silver_df),
        "category_breakdown": category_breakdown(silver_df),
        "account_summary": account_summary(silver_df),
        "health_metrics": health_metrics(silver_df),
    }
    for name, table in tables.items():
        path = write_table(table, cfg, "gold", DATASET, name)
        print(f"[gold] {name}: {len(table)} rows -> {path}")

    generate_report(tables, cfg)
    return tables


def generate_report(tables: dict[str, pd.DataFrame], cfg: dict) -> Path:
    """Render a human-readable Markdown report from gold tables."""
    out_dir = Path(cfg["reporting"]["output_dir"])
    out_dir.mkdir(parents=True, exist_ok=True)
    out = out_dir / "financial_report.md"

    m = tables["monthly_summary"]
    h = tables["health_metrics"].iloc[0]
    best = m.loc[m["total_spend"].idxmax()]

    lines = [
        "# Financial Transactions Report",
        "",
        "## Key numbers",
        f"- Total transactions analyzed: **{int(h['total_transactions']):,}**",
        f"- Refund rate: **{h['refund_rate_pct']}%** | Failure rate: **{h['failure_rate_pct']}%**",
        f"- Peak month: **{int(best['year'])}-{int(best['month']):02d}** "
        f"with **{best['total_spend']:,.2f}** total spend",
        "",
        "## Monthly trend",
        m.to_markdown(index=False),
        "",
        "## Top merchants",
        tables["top_merchants"].to_markdown(index=False),
        "",
        "## Spend by category",
        tables["category_breakdown"].to_markdown(index=False),
        "",
        "_Generated by finlake gold zone._",
    ]
    out.write_text("\n".join(lines))
    print(f"[gold] report -> {out}")
    return out
